### ISSUE TITLE
1

### ISSUE THREAD

**Issue by oneLeaf2012** [258806121/HXMExpandAndFlod#1]

**Comment by 258806121** [comment]
这个是我随便写的一个小demo 主要是为了写一个可以展开的label问题,置于放在cell中显示的话,可以在代理方法中动态设置约束,置于你说的问题,在封装的expandLbel中,可以修改.

**Comment by oneLeaf2012** [comment]
有时间请更正此问题，我会继续跟踪，目前我也在做这个效果 ，我看到这个 expandLbel封装的非常好，但是还是有不足的地方，我经过排查，也没有排查出是哪里的问题，需要原作者协助一下，谢谢

**Comment by oneLeaf2012** [comment]
> _No description provided._
